# Generated by Django 5.0.6 on 2024-07-12 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kitob',
        ),
        migrations.DeleteModel(
            name='Kutibxona',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
