# Generated by Django 5.0.7 on 2024-07-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dokon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('price', models.IntegerField()),
                ('img', models.ImageField(upload_to='kitob/')),
                ('commints', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tarix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('price', models.IntegerField()),
                ('img', models.ImageField(upload_to='kitob/')),
                ('commints', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
